### PR TITLE
Avoid nan when computing loss in softmax_cross_entropy

### PR DESCRIPTION
**Pull request by byzhang**
Also generates compile_commands.json so YCM can work with the code base.

### CODE REVIEW

**Comment by byzhang** [comment]
It has the following errors now:
```
tensor/op/cost.cu.cpp.cu(316): error: too many arguments in function call
          detected during instantiation of "Mat<R> matops::Cost<R>::softmax_cross_entropy_colwise(Mat<R>, Mat<int>) [with R=float]"
(303): here
```

**Comment by byzhang** [comment]
Is it a right function to call?
```
MAT(out) = (R)-1.0 * F<op::log<R>>(MAT(MatOps<R>::eltmax(out, std::numeric_limits<R>::min())).wrapper());
```

**Comment by byzhang** [comment]
@nivwusquorum ^^^

**Comment by JonathanRaiman** [comment]
This is correct, however `MatOps<R>::eltmax` will allocate extra memory and return a new mat,
so what you want instead is:

```
MAT(out) = (R)-1.0 * F<op::log<R>>(
                                     F<op::max_scalar>(
                                         MAT(out).wrapper(), std::numeric_limits<R>::min()
                                     )
                                 );
```

However, there is a slight risk that log(std::numeric_limits<R>::min()) still gives you an infinity (which might undo the safety check you were performing here)

**Comment by byzhang** [comment]
Yes, for long double, log(std::numeric_limits::min()) is -inf. As it's for
safety, how about using std::numeric_limits<float>::min() directly?

btw, your example cannot compile:
```
error: no instance of overloaded function "F" matches the argument list
argument types are: (LazyTensor<mshadow::Tensor<mshadow::cpu, 2, double>,
mshadow::Tensor<mshadow::gpu, 2, double>, double, 2, 0>, double) detected
during instantiation of "Mat<R>
matops::Cost<R>::softmax_cross_entropy_rowwise(Mat<R>, Mat<int>) [with
R=double]" (350): here
```

Thanks,
-B

**Comment by JonathanRaiman** [comment]
Yes; I'm not sure if you want to wrap the whole expression in another max to yield a -inf if you get log(min).

As for the code, yes I forgot to template the functor for F:

```
MAT(out) = (R)-1.0 * F<op::log<R>>(
                                     F<op::max_scalar<R>>(
                                         MAT(out).wrapper(), std::numeric_limits<R>::min()
                                     )
                                 );
```

**Pull request closed without merging**
